title: Romanos Rizk
logo: /Assets/LinkedIn01-cropped.jpeg
description: Proactive MSc in Business Analytics student at the American University of Beirut with strong academic achievements and relevant experience. Possess strong leadership and communication skills in English, French, and Arabic. Passionate about data, how to manipulate it, and how to analyze it for strategic and research purposes. I currently focus on improving my data modeling and manipulation skills using various tools such as Excel, R, SQL, and Python.
#show_downloads: true
theme: jekyll-theme-minimal
